[33mcommit 1e72beb87efb86e28979073bc7f45ad2b3adc93d[m[33m ([m[1;36mHEAD -> [m[1;32mmaster[m[33m)[m
Author: khac thang <thanglkph19992@fpt.edu.vn>
Date:   Fri Sep 15 14:22:49 2023 +0700

    add one APP.js

[33mcommit b6bef6f36d19a538a6a51ae44f1eba39dbe9ab8a[m
Author: khac thang <thanglkph19992@fpt.edu.vn>
Date:   Fri Sep 15 13:34:18 2023 +0700

    Initial commit
    
    Generated by create-expo-app 1.1.4.
